import cz from "./lang/cz.json";
import de from "./lang/de.json";
import en from "./lang/en.json";
import es from "./lang/es.json";
import fr from "./lang/fr.json";
import it from "./lang/it.json";
import ja from "./lang/ja.json";
import ko from "./lang/ko.json";
import nl from "./lang/nl.json";
import pl from "./lang/pl.json";
import pt from "./lang/pt.json";
import ru from "./lang/ru.json";
import sv from "./lang/sv.json";
import uk from "./lang/uk.json";
import vi from "./lang/vi.json";
import zh_tw from "./lang/zh_tw.json";
import zh from "./lang/zh.json";

Language.addTranslations("cz", cz);
Language.addTranslations("de", de);
Language.addTranslations("en", en);
Language.addTranslations("es", es);
Language.addTranslations("fr", fr);
Language.addTranslations("it", it);
Language.addTranslations("ja", ja);
Language.addTranslations("ko", ko);
Language.addTranslations("nl", nl);
Language.addTranslations("pl", pl);
Language.addTranslations("pt", pt);
Language.addTranslations("ru", ru);
Language.addTranslations("sv", sv);
Language.addTranslations("uk", uk);
Language.addTranslations("vi", vi);
Language.addTranslations("zh_tw", zh_tw);
Language.addTranslations("zh", zh);
