export const rotationTypes = [
    "default",
    //"axis",
    //"y_axis_player",
    "y_axis",
    //"all_player",
    //"all",
];

export const soundOptions = [
    "Grass",
    "Glass",
    "Gravel",
    "Honey",
    "Metal",
    "Sand",
    "Snow",
    "Stone",
    "Wool",
    "Wood",
    "Ancient Debris",
    "Anvil",
    "Bamboo",
    "Bamboo Sapling",
    "Basalt",
    "Bone Brick",
    "Chain",
    "Coral Block",
    "Crop",
    "Fungus",
    "Gilded Blackstone",
    "Hard Crop",
    "Ladder",
    "Lantern",
    "Lily Pad",
    "Lodestone",
    "Netherite Block",
    "Netherrack",
    "Nether Bricks",
    "Nether Gold Ore",
    "Nether Ore",
    "Nether Sprouts",
    "Nether Wart",
    "Nylium",
    "Roots",
    "Scaffolding",
    "Shroomlight",
    "Slime Block",
    "Soul Sand",
    "Stem",
    "Sweet Berry Bush",
    "Twisting Vines",
    "Vine",
    "Wart Block",
    "Weeping Vines",
    "Wet Grass"
];

export const materialOptions = [
    "Dirt",        
    "Air",
    "Bamboo",
    "Bamboo Sapling",
    "Barrier",
    "Bubble Column",
    "Buildable Glass",
    "Cactus",
    "Cake",
    "Clay",
    "Coral",
    "Cloth Decoration",
    "Decoration",
    "Egg",
    "Explosive",
    "Fire",
    "Glass",
    "Grass",
    "Heavy Metal",
    "Ice",
    "Ice Solid",
    "Lava",
    "Leaves",
    "Metal",
    "Nether Wood",
    "Piston",
    "Plant",
    "Portal",
    "Replaceable Plant",
    "Replaceable Fireproof Plant",
    "Replaceable Water Plant",
    "Sand",
    "Shulker Shell",
    "Snow",
    "Sponge",
    "Stone",
    "Structural Air",
    "Top Snow",
    "Vegetable",
    "Water",
    "Water Plant",
    "Web",
    "Wood",
    "Wool"
];

export const transparencyOptions = [
    "Solid",
    "Translucent",
    "Cutout",
    "Cutout (Mipped)"
];

export const tabOptions = [
    "Building Blocks",
    "Brewing",
    "Combat",
    "Food",
    "Decorations",
    "Misc",
    "Redstone",
    "Tools",
    "Transportation"
];

export const particleOptions = [
    "Ambient Entity Effect",
    "Angry Villager",
    "Ash",
    "Bubble",
    "Bubble Pop",
    "Campfire Smoke",
    "Cloud",
    "Composter",
    "Crimson Spore",
    "Crit",
    "Damage Indicator",
    "Dolphin",
    "Dripping Dripstone Lava",
    "Dripping Dripstone Water",
    "Dripping Honey",
    "Dripping Lava",
    "Dripping Obsidian Tear",
    "Dripping Water",
    "Elder Guardian",
    "Electric Spark",
    "Enchant",
    "Enchanted Hit",
    "End Rod",
    "Entity Effect",
    "Explosion",
    "Falling Dripstone Lava",
    "Falling Dripstone Water",
    "Falling Honey",
    "Falling Lava",
    "Falling Nectar",
    "Falling Obsidian Tear",
    "Falling Spore Blossom",
    "Falling Water",
    "Firework",
    "Fishing",
    "Flame",
    "Flash",
    "Glow",
    "Glow Squid Ink",
    "Happy Villager",
    "Heart",
    "Slime Item",
    "Snowball item",
    "Landing Honey",
    "Landing Lava",
    "Landing Obsidian Tear",
    "Lava",
    "Mycelium",
    "Nautilus",
    "Note",
    "Rain",
    "Reverse Portal",
    "Scrape",
    "Small Flame",
    "Snowflake",
    "Soul",
    "Soulfire Flame",
    "Spore Blossom Air",
    "Sweep Attack",
    "Totem of Undying",
    "Undewater",
    "Warped Spore",
    "Wax off",
    "Wax On",
    "White Ash",
    "Witch",

];

export const customTypeOptions = ["Default", "Flower"];

export default {rotationTypes, soundOptions, materialOptions, transparencyOptions, tabOptions, customTypeOptions};