RenderStudio.presetStorageKey = 'render_studio_user_presets_v1';
RenderStudio.history = [];
RenderStudio.readUserPresets = () => {
  try { const value=JSON.parse(localStorage.getItem(RenderStudio.presetStorageKey)||'{}');return value&&typeof value==='object'?value:{}; }
  catch (error) { console.warn('[Render Studio] Could not read presets', error); return {}; }
};
RenderStudio.writeUserPresets = presets => {
  try { localStorage.setItem(RenderStudio.presetStorageKey,JSON.stringify(presets));return true; }
  catch (error) { Blockbench.showQuickMessage('Could not save preset on this device');return false; }
};
RenderStudio.presetPayload = state => {
  const data=RenderStudio.serializeState(state);delete data.environment.imageSource;delete data.environment.imageData;delete data.environment.imageName;delete data.output.width;delete data.output.height;return data;
};
RenderStudio.saveUserPreset = name => {
  name=String(name||'').trim().slice(0,40);if(!name){Blockbench.showQuickMessage('Enter a preset name');return false;}
  const presets=RenderStudio.readUserPresets();presets[name]=RenderStudio.presetPayload(RenderStudio.getState());
  if(RenderStudio.writeUserPresets(presets)){Blockbench.showQuickMessage(`Saved preset: ${name}`);RenderStudio.refreshUI();return true;}return false;
};
RenderStudio.applyUserPreset = name => {
  const saved=RenderStudio.readUserPresets()[name];if(!saved)return;
  const s=RenderStudio.getState(),hydrated=RenderStudio.hydrateState(saved),keep={output:RenderStudio.cloneData(s.output),imageSource:s.environment.imageSource,imageData:s.environment.imageData,imageName:s.environment.imageName};
  for(const key of ['lights','selectedLight','helpers','helperSize','ambient','hemisphere','ground','material','camera','post','tools'])if(hydrated[key]!==undefined)s[key]=RenderStudio.cloneData(hydrated[key]);
  Object.assign(s.environment,hydrated.environment,{imageSource:keep.imageSource,imageData:keep.imageData,imageName:keep.imageName});Object.assign(s.output,hydrated.output,keep.output);
  if(RenderStudio.engine)RenderStudio.engine.rebuild();RenderStudio.touch();RenderStudio.refreshUI();
};
RenderStudio.deleteUserPreset = name => {const presets=RenderStudio.readUserPresets();if(!(name in presets))return;delete presets[name];RenderStudio.writeUserPresets(presets);RenderStudio.refreshUI();};

RenderStudio.applyCameraPreset = name => {
  const s=RenderStudio.getState(),sizes={square:[1024,1024],portrait:[1080,1350],landscape:[1920,1080],item:[512,512],profile:[1024,1024]},size=sizes[name]||sizes.square,fit=RenderStudio.constrainOutput(size[0],size[1],s.performance);
  s.tools.cameraPreset=name;s.output.width=fit.width;s.output.height=fit.height;
  if(RenderStudio.engine){RenderStudio.engine.frameModel(true);if(name==='profile')RenderStudio.engine.zoom(.78);if(name==='item')RenderStudio.engine.zoom(.88);}
  RenderStudio.touch();RenderStudio.refreshUI();
};

RenderStudio.canvasBlob = canvas => new Promise((resolve,reject)=>{if(canvas.toBlob)canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('Could not encode image')),'image/png');else{try{const parts=canvas.toDataURL('image/png').split(','),bytes=atob(parts[1]),array=new Uint8Array(bytes.length);for(let i=0;i<bytes.length;i++)array[i]=bytes.charCodeAt(i);resolve(new Blob([array],{type:'image/png'}));}catch(error){reject(error);}}});
RenderStudio.exportBlob = (blob,name,extension,type) => Blockbench.export({resource_id:'render_studio_export',type:type||'Render Studio Export',extensions:[extension],name,savetype:extension,content:blob});

RenderStudio.renderTurntable = async () => {
  const engine=RenderStudio.engine,s=RenderStudio.getState();if(!engine||s.render.busy)return;
  if(typeof JSZip!=='function'){Blockbench.showMessageBox({title:'Turntable Render',message:'ZIP support is unavailable in this Blockbench build.'});return;}
  const frames=RenderStudio.clamp(s.tools.turntableFrames,4,s.performance==='phone'?24:120),zip=new JSZip(),camera=RenderStudio.cloneData(s.camera),target=new THREE.Vector3().fromArray(camera.target),offset=new THREE.Vector3().fromArray(camera.position).sub(target);
  s.render.busy=true;s.render.cancel=false;
  try{
    for(let i=0;i<frames;i++){
      if(s.render.cancel)throw new Error('Render cancelled');
      const angle=Math.PI*2*i/frames,rotated=offset.clone().applyAxisAngle(new THREE.Vector3(0,1,0),angle);s.camera.position=target.clone().add(rotated).toArray();engine.updateCamera();
      s.render.status=`Turntable ${i+1} / ${frames}`;s.render.progress=Math.round(i/frames*100);RenderStudio.refreshUI();
      const canvas=await engine.renderImage({show:false,history:false,manageBusy:false});zip.file(`frame_${String(i+1).padStart(3,'0')}.png`,await RenderStudio.canvasBlob(canvas));
    }
    const content=await zip.generateAsync({type:'blob',compression:'DEFLATE',compressionOptions:{level:6}});RenderStudio.exportBlob(content,`${RenderStudio.safeName(Project&&Project.name)}_turntable`,'zip','Turntable PNG Frames');
  }catch(error){if(error.message!=='Render cancelled')Blockbench.showMessageBox({title:'Turntable Failed',message:String(error.message||error)});}
  finally{Object.assign(s.camera,camera);engine.updateCamera();s.render.busy=false;s.render.status='';s.render.progress=0;RenderStudio.refreshUI();}
};

RenderStudio.processBackgroundImage = (dataUrl,blur,brightness) => new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>{const max=RenderStudio.isMobile()?1024:2048,scale=Math.min(1,max/Math.max(image.width,image.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));const ctx=canvas.getContext('2d');if(!ctx){reject(new Error('Could not process background image'));return;}ctx.filter=`blur(${RenderStudio.clamp(blur,0,30)}px) brightness(${RenderStudio.clamp(brightness,.1,3)})`;const pad=RenderStudio.clamp(blur,0,30)*2;ctx.drawImage(image,-pad,-pad,canvas.width+pad*2,canvas.height+pad*2);resolve(canvas.toDataURL('image/jpeg',.9));};image.onerror=()=>reject(new Error('Could not read background image'));image.src=dataUrl;});
RenderStudio.loadBackgroundFile = event => {
  const file=event&&event.target&&event.target.files&&event.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=async()=>{try{const s=RenderStudio.getState();s.environment.imageSource=reader.result;s.environment.imageData=await RenderStudio.processBackgroundImage(s.environment.imageSource,s.environment.imageBlur,s.environment.imageBrightness);s.environment.imageName=file.name;s.environment.background='image';if(RenderStudio.engine)RenderStudio.engine.rebuildEnvironment();RenderStudio.touch();RenderStudio.refreshUI();}catch(error){Blockbench.showMessageBox({title:'Background Image',message:String(error.message||error)});}};reader.readAsDataURL(file);
};
RenderStudio.refreshBackgroundImage = async () => {const s=RenderStudio.getState();if(!s.environment.imageSource)return;try{s.environment.imageData=await RenderStudio.processBackgroundImage(s.environment.imageSource,s.environment.imageBlur,s.environment.imageBrightness);if(RenderStudio.engine)RenderStudio.engine.rebuildEnvironment();RenderStudio.touch();}catch(error){console.warn('[Render Studio] Background update failed',error);}};
RenderStudio.clearBackgroundImage = () => {const s=RenderStudio.getState();s.environment.imageSource='';s.environment.imageData='';s.environment.imageName='';if(s.environment.background==='image')s.environment.background='transparent';if(RenderStudio.engine)RenderStudio.engine.rebuildEnvironment();RenderStudio.touch();RenderStudio.refreshUI();};

RenderStudio.applyCanvasEffects = canvas => {
  const p=RenderStudio.getState().post;if(!p||(!p.bloom&&!p.vignette&&!p.contrast&&!p.saturation&&!p.dof))return canvas;
  const out=document.createElement('canvas');out.width=canvas.width;out.height=canvas.height;const ctx=out.getContext('2d',{alpha:true});if(!ctx)return canvas;
  const contrast=100+RenderStudio.clamp(p.contrast,-100,100),saturation=100+RenderStudio.clamp(p.saturation,-100,200),blur=RenderStudio.clamp(p.dof,0,12);ctx.filter=`contrast(${contrast}%) saturate(${saturation}%) blur(${blur}px)`;ctx.drawImage(canvas,0,0);ctx.filter='none';
  if(p.bloom){ctx.save();ctx.globalCompositeOperation='screen';ctx.globalAlpha=RenderStudio.clamp(p.bloomStrength,0,2)*.35;ctx.filter=`blur(${Math.max(4,Math.round(Math.min(canvas.width,canvas.height)/100))}px) brightness(140%)`;ctx.drawImage(canvas,0,0);ctx.restore();}
  if(p.vignette>0){const amount=RenderStudio.clamp(p.vignette,0,1),g=ctx.createRadialGradient(out.width/2,out.height/2,Math.min(out.width,out.height)*.2,out.width/2,out.height/2,Math.max(out.width,out.height)*.72);g.addColorStop(0,'rgba(0,0,0,0)');g.addColorStop(1,`rgba(0,0,0,${amount})`);ctx.fillStyle=g;ctx.fillRect(0,0,out.width,out.height);}
  return out;
};

RenderStudio.dataURLBlob = dataURL => {const parts=dataURL.split(','),mime=(parts[0].match(/data:([^;]+)/)||[])[1]||'application/octet-stream',bytes=atob(parts[1]),array=new Uint8Array(bytes.length);for(let i=0;i<bytes.length;i++)array[i]=bytes.charCodeAt(i);return new Blob([array],{type:mime});};
RenderStudio.addHistory = (canvas,pass='beauty') => {const entry={id:RenderStudio.uid(),url:canvas.toDataURL('image/png'),width:canvas.width,height:canvas.height,pass,time:new Date().toLocaleTimeString()};RenderStudio.history.unshift(entry);const limit=RenderStudio.isMobile()?5:10;while(RenderStudio.history.length>limit)RenderStudio.history.pop();const tools=RenderStudio.getState().tools;tools.compareA=RenderStudio.history[0]&&RenderStudio.history[0].id||'';tools.compareB=RenderStudio.history[1]&&RenderStudio.history[1].id||'';RenderStudio.refreshUI();return entry;};
RenderStudio.openHistory = id => {const item=RenderStudio.history.find(entry=>entry.id===id);if(!item)return;new Dialog('render_studio_history_item',{title:`Render History · ${item.pass}`,width:Math.min(900,window.innerWidth-40),component:{data(){return{item}},template:'<div class="rs-result"><div>{{item.width}} × {{item.height}}</div><img :src="item.url"></div>'},buttons:['Save PNG','Close'],onButton:i=>{if(i===0)RenderStudio.exportBlob(RenderStudio.dataURLBlob(item.url),`${RenderStudio.safeName(Project&&Project.name)}_${item.pass}_${item.width}x${item.height}`,'png','Render History PNG');}}).show();};
RenderStudio.clearHistory = () => {RenderStudio.history.splice(0);const tools=RenderStudio.getState().tools;tools.compareA='';tools.compareB='';RenderStudio.refreshUI();};

// Render Studio 2.1 workflow tools
RenderStudio.i18n = {
  en:{simple:'Simple',advanced:'Advanced',category_general:'General',category_workflow:'Workflow',category_look:'Look & Style',category_output:'Render Output',category_scene:'Scene Extras',category_batch:'Batch & Export',category_support:'System & Support',language:'Language',automatic_device:'Automatic device profile',detected:'Detected profile',phone:'Phone / Low PC',pc:'PC',undo:'Undo',redo:'Redo',comparison:'Render Comparison',side_by_side:'Side by side',slider:'Slider',compare:'Compare',preset_share:'Preset Import / Export',import_preset:'Import JSON',export_presets:'Export Presets',queue:'Render Queue',add_queue:'Add to Queue',run_queue:'Render Queue as ZIP',clear:'Clear',watermark:'Watermark / Logo',enabled:'Enabled',text:'Text',image:'Logo image',position:'Position',opacity:'Opacity',size:'Size',diagnostics:'Error Report',copy_report:'Copy Device Report',search:'Search advanced settings…',no_results:'No matching settings',history:'Render History',select_a:'Select A',select_b:'Select B'},
  tr:{simple:'Basit',advanced:'Gelişmiş',category_general:'Genel',category_workflow:'İş Akışı',category_look:'Görünüm ve Stil',category_output:'Render Çıktısı',category_scene:'Sahne Araçları',category_batch:'Toplu İşlem ve Dışa Aktarma',category_support:'Sistem ve Destek',language:'Dil',automatic_device:'Otomatik cihaz profili',detected:'Algılanan profil',phone:'Telefon / Düşük PC',pc:'PC',undo:'Geri Al',redo:'Yinele',comparison:'Render Karşılaştırma',side_by_side:'Yan yana',slider:'Sürgü',compare:'Karşılaştır',preset_share:'Preset İçe / Dışa Aktarma',import_preset:'JSON İçe Aktar',export_presets:'Presetleri Dışa Aktar',queue:'Render Kuyruğu',add_queue:'Kuyruğa Ekle',run_queue:'Kuyruğu ZIP Olarak Renderla',clear:'Temizle',watermark:'Filigran / Logo',enabled:'Etkin',text:'Yazı',image:'Logo görseli',position:'Konum',opacity:'Saydamlık',size:'Boyut',diagnostics:'Hata Raporu',copy_report:'Cihaz Raporunu Kopyala',search:'Gelişmiş ayarlarda ara…',no_results:'Eşleşen ayar yok',history:'Render Geçmişi',select_a:'A seç',select_b:'B seç'}
};
RenderStudio.t = key => {const language=(RenderStudio.getState().tools||{}).language==='tr'?'tr':'en';return RenderStudio.i18n[language][key]||RenderStudio.i18n.en[key]||key;};
RenderStudio.scrubNumberValue = (start,deltaY,step,min,max) => {step=Math.abs(Number(step))||1;let value=Number(start)+(Number(deltaY)||0)/8*step;const decimals=Math.min(6,Math.max(0,(String(step).split('.')[1]||'').length));value=Number(value.toFixed(decimals));if(Number.isFinite(Number(min)))value=Math.max(Number(min),value);if(Number.isFinite(Number(max)))value=Math.min(Number(max),value);return value;};
RenderStudio.installNumberScrubbing = () => {
  if(typeof document==='undefined'||!document.querySelectorAll)return;
  const bound=new WeakSet(),cleanups=[];
  const bind=root=>{if(!root||bound.has(root)||!root.addEventListener)return;bound.add(root);let drag=null;
    const down=event=>{const input=event.target;if(!input||!input.matches||!input.matches('input[type="number"]')||(event.pointerType!=='touch'&&event.button!==0))return;drag={input,pointerId:event.pointerId,startY:event.clientY,start:Number(input.value)||0,step:Number(input.step)||1,min:input.min,max:input.max,moved:false};RenderStudio.beginUndoAction();input.setPointerCapture&&input.setPointerCapture(event.pointerId);};
    const move=event=>{if(!drag||event.pointerId!==drag.pointerId)return;const distance=drag.startY-event.clientY;if(!drag.moved&&Math.abs(distance)<5)return;drag.moved=true;drag.input.classList&&drag.input.classList.add('rs-number-scrubbing');drag.input.value=String(RenderStudio.scrubNumberValue(drag.start,distance,drag.step,drag.min,drag.max));drag.input.dispatchEvent(new Event('input',{bubbles:true}));event.preventDefault();};
    const up=event=>{if(!drag||event.pointerId!==drag.pointerId)return;const active=drag;drag=null;if(active.moved){active.input.dispatchEvent(new Event('change',{bubbles:true}));active.input.blur&&active.input.blur();event.preventDefault();}active.input.classList&&active.input.classList.remove('rs-number-scrubbing');RenderStudio.endUndoAction();};
    root.addEventListener('pointerdown',down,true);root.addEventListener('pointermove',move,{capture:true,passive:false});root.addEventListener('pointerup',up,true);root.addEventListener('pointercancel',up,true);cleanups.push(()=>{root.removeEventListener('pointerdown',down,true);root.removeEventListener('pointermove',move,true);root.removeEventListener('pointerup',up,true);root.removeEventListener('pointercancel',up,true);});};
  const scan=()=>{for(const root of document.querySelectorAll('#panel_render_studio_scene,#panel_render_studio_settings,#panel_render_studio_tools'))bind(root);};scan();const first=setTimeout(scan,0),second=setTimeout(scan,250);
  RenderStudio.resources.push({delete(){clearTimeout(first);clearTimeout(second);cleanups.splice(0).forEach(cleanup=>cleanup());}});
};
RenderStudio.detectDeviceProfile = (apply=true) => {
  let score=0;const nav=typeof navigator==='undefined'?{}:navigator;
  if(RenderStudio.isMobile())score+=4;
  if(Number(nav.deviceMemory)&&Number(nav.deviceMemory)<=4)score+=2;
  if(Number(nav.hardwareConcurrency)&&Number(nav.hardwareConcurrency)<=4)score+=1;
  try{if(window.matchMedia&&window.matchMedia('(pointer: coarse)').matches)score+=2;}catch(error){}
  const profile=score>=2?'phone':'pc',s=RenderStudio.getState();
  if(apply&&s.tools.autoProfile&&s.performance!==profile)RenderStudio.applyPerformanceProfile(profile);
  return profile;
};
RenderStudio.setAutoProfile = enabled => {const s=RenderStudio.getState();s.tools.autoProfile=!!enabled;if(enabled)RenderStudio.detectDeviceProfile();RenderStudio.touch();RenderStudio.refreshUI();};

RenderStudio.undoStack=[];RenderStudio.redoStack=[];RenderStudio.undoLimit=40;RenderStudio.undoBefore=null;RenderStudio.observedUndoSnapshot=null;RenderStudio.applyingUndo=false;
RenderStudio.undoSnapshot = () => {const s=RenderStudio.getState();return RenderStudio.cloneData({camera:s.camera,lights:s.lights,selectedLight:s.selectedLight});};
RenderStudio.undoFingerprint = value => JSON.stringify(value||RenderStudio.undoSnapshot());
RenderStudio.beginUndoAction = () => {if(!RenderStudio.undoBefore)RenderStudio.undoBefore=RenderStudio.undoSnapshot();};
RenderStudio.endUndoAction = () => {if(!RenderStudio.undoBefore)return false;const before=RenderStudio.undoBefore,after=RenderStudio.undoSnapshot();RenderStudio.undoBefore=null;RenderStudio.observedUndoSnapshot=RenderStudio.cloneData(after);if(RenderStudio.undoFingerprint(before)===RenderStudio.undoFingerprint(after))return false;RenderStudio.undoStack.push(before);while(RenderStudio.undoStack.length>RenderStudio.undoLimit)RenderStudio.undoStack.shift();RenderStudio.redoStack.splice(0);RenderStudio.touch();RenderStudio.refreshUI();return true;};
RenderStudio.resetUndoObserver = () => {RenderStudio.undoBefore=null;RenderStudio.undoStack.splice(0);RenderStudio.redoStack.splice(0);RenderStudio.observedUndoSnapshot=RenderStudio.undoSnapshot();};
RenderStudio.observeUndoState = () => {const current=RenderStudio.undoSnapshot();if(RenderStudio.applyingUndo||RenderStudio.undoBefore){return;}if(!RenderStudio.observedUndoSnapshot){RenderStudio.observedUndoSnapshot=current;return;}if(RenderStudio.undoFingerprint(current)===RenderStudio.undoFingerprint(RenderStudio.observedUndoSnapshot))return;RenderStudio.undoStack.push(RenderStudio.cloneData(RenderStudio.observedUndoSnapshot));while(RenderStudio.undoStack.length>RenderStudio.undoLimit)RenderStudio.undoStack.shift();RenderStudio.redoStack.splice(0);RenderStudio.observedUndoSnapshot=current;};
RenderStudio.applyUndoSnapshot = snapshot => {const s=RenderStudio.getState();RenderStudio.applyingUndo=true;s.camera=RenderStudio.cloneData(snapshot.camera);s.lights=RenderStudio.cloneData(snapshot.lights);s.selectedLight=snapshot.selectedLight;RenderStudio.observedUndoSnapshot=RenderStudio.cloneData(snapshot);if(RenderStudio.engine){RenderStudio.engine.updateCamera();RenderStudio.engine.rebuildLights();RenderStudio.engine.invalidate();}RenderStudio.touch();RenderStudio.refreshUI();RenderStudio.applyingUndo=false;};
RenderStudio.undo = () => {const snapshot=RenderStudio.undoStack.pop();if(!snapshot)return;RenderStudio.redoStack.push(RenderStudio.undoSnapshot());RenderStudio.applyUndoSnapshot(snapshot);};
RenderStudio.redo = () => {const snapshot=RenderStudio.redoStack.pop();if(!snapshot)return;RenderStudio.undoStack.push(RenderStudio.undoSnapshot());RenderStudio.applyUndoSnapshot(snapshot);};
RenderStudio.recordChange = callback => {RenderStudio.beginUndoAction();try{return callback&&callback();}finally{RenderStudio.endUndoAction();}};

RenderStudio.exportPresets = () => {const content=JSON.stringify({format:'render-studio-presets',version:1,pluginVersion:RenderStudio.VERSION,presets:RenderStudio.readUserPresets()},null,2);Blockbench.export({resource_id:'render_studio_presets',type:'Render Studio Presets',extensions:['json'],name:'render_studio_presets',savetype:'text',content});};
RenderStudio.importPresets = event => {const file=event&&event.target&&event.target.files&&event.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(String(reader.result||'')),incoming=data&&data.format==='render-studio-presets'?data.presets:data;if(!incoming||typeof incoming!=='object'||Array.isArray(incoming))throw new Error('Invalid Render Studio preset file');const presets=RenderStudio.readUserPresets();let count=0;for(const [name,value] of Object.entries(incoming)){if(value&&typeof value==='object'){presets[String(name).slice(0,40)]=value;count++;}}if(!count)throw new Error('No presets found');RenderStudio.writeUserPresets(presets);RenderStudio.refreshUI();Blockbench.showQuickMessage(`${count} preset${count===1?'':'s'} imported`);}catch(error){Blockbench.showMessageBox({title:'Preset Import',message:String(error.message||error)});}finally{if(event.target)event.target.value='';}};reader.readAsText(file);};

RenderStudio.openComparison = () => {const s=RenderStudio.getState(),a=RenderStudio.history.find(item=>item.id===s.tools.compareA),b=RenderStudio.history.find(item=>item.id===s.tools.compareB);if(!a||!b){Blockbench.showQuickMessage('Select two renders first');return;}const slider=s.tools.compareMode==='slider';new Dialog('render_studio_compare',{title:RenderStudio.t('comparison'),width:Math.min(1000,window.innerWidth-32),component:{data(){return{a,b,slider,split:50}},template:`<div class="rs-compare" :class="{slider:slider}"><template v-if="!slider"><figure><img :src="a.url"><figcaption>A · {{a.time}}</figcaption></figure><figure><img :src="b.url"><figcaption>B · {{b.time}}</figcaption></figure></template><template v-else><div class="rs-compare-stage"><img :src="a.url"><div class="rs-compare-top" :style="{width:split+'%'}"><img :src="b.url"></div><i :style="{left:split+'%'}"></i></div><input type="range" min="0" max="100" v-model.number="split"></template></div>`},buttons:['Close']}).show();};

RenderStudio.addQueueItem = () => {const s=RenderStudio.getState(),preset=s.tools.queuePreset||'',camera=s.tools.queueCamera||'square';s.tools.renderQueue.push({id:RenderStudio.uid(),name:`${preset||'Current'} · ${camera}`,preset,camera,pass:s.output.pass||'beauty'});RenderStudio.touch();RenderStudio.refreshUI();};
RenderStudio.removeQueueItem = id => {const q=RenderStudio.getState().tools.renderQueue,i=q.findIndex(item=>item.id===id);if(i>=0)q.splice(i,1);RenderStudio.touch();RenderStudio.refreshUI();};
RenderStudio.runRenderQueue = async () => {const s=RenderStudio.getState(),engine=RenderStudio.engine,items=s.tools.renderQueue.slice();if(!engine||!items.length||s.render.busy)return;if(typeof JSZip!=='function'){Blockbench.showMessageBox({title:'Render Queue',message:'ZIP support is unavailable.'});return;}const backup=RenderStudio.serializeState(s),zip=new JSZip();s.render.busy=true;s.render.cancel=false;try{for(let i=0;i<items.length;i++){if(s.render.cancel)throw new Error('Render cancelled');const item=items[i];if(item.preset)RenderStudio.applyUserPreset(item.preset);RenderStudio.applyCameraPreset(item.camera);s.render.status=`Queue ${i+1} / ${items.length}: ${item.name}`;s.render.progress=Math.round(i/items.length*100);const canvas=await engine.renderImage({pass:item.pass,show:false,manageBusy:false});zip.file(`${String(i+1).padStart(2,'0')}_${RenderStudio.safeName(item.name)}.png`,await RenderStudio.canvasBlob(canvas));}const content=await zip.generateAsync({type:'blob',compression:'DEFLATE',compressionOptions:{level:6}});RenderStudio.exportBlob(content,`${RenderStudio.safeName(Project&&Project.name)}_render_queue`,'zip','Render Queue');}catch(error){if(error.message!=='Render cancelled')Blockbench.showMessageBox({title:'Render Queue Failed',message:String(error.message||error)});}finally{const restored=RenderStudio.hydrateState(backup);for(const key of ['lights','selectedLight','helpers','helperSize','ambient','hemisphere','ground','material','camera','environment','output','post','tools'])s[key]=RenderStudio.cloneData(restored[key]);s.render.busy=false;s.render.status='';s.render.progress=0;engine.rebuild();RenderStudio.touch();RenderStudio.refreshUI();}};

RenderStudio.loadWatermark = event => {const file=event&&event.target&&event.target.files&&event.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{const s=RenderStudio.getState();s.tools.watermarkImage=String(reader.result||'');s.tools.watermarkName=file.name;s.tools.watermarkEnabled=true;RenderStudio.touch();RenderStudio.refreshUI();};reader.readAsDataURL(file);};
RenderStudio.applyWatermark = async canvas => {const w=RenderStudio.getState().tools;if(!w.watermarkEnabled||(!w.watermarkImage&&!w.watermarkText))return canvas;const out=document.createElement('canvas');out.width=canvas.width;out.height=canvas.height;const ctx=out.getContext('2d',{alpha:true});if(!ctx)return canvas;ctx.drawImage(canvas,0,0);ctx.globalAlpha=RenderStudio.clamp(w.watermarkOpacity,0,1);const margin=Math.max(8,Math.round(Math.min(out.width,out.height)*.025)),position=w.watermarkPosition||'bottom-right';if(w.watermarkImage){await new Promise(resolve=>{const image=new Image();image.onload=()=>{const target=Math.max(16,out.width*RenderStudio.clamp(w.watermarkScale,2,60)/100),scale=Math.min(target/image.width,out.height*.5/image.height),iw=image.width*scale,ih=image.height*scale,x=position.includes('right')?out.width-iw-margin:margin,y=position.includes('bottom')?out.height-ih-margin:margin;ctx.drawImage(image,x,y,iw,ih);resolve();};image.onerror=resolve;image.src=w.watermarkImage;});}if(w.watermarkText){const size=Math.max(12,Math.round(out.width*RenderStudio.clamp(w.watermarkScale,2,60)/300));ctx.font=`600 ${size}px sans-serif`;ctx.fillStyle='#ffffff';ctx.shadowColor='rgba(0,0,0,.8)';ctx.shadowBlur=Math.max(2,size/8);ctx.textBaseline='bottom';const width=ctx.measureText(w.watermarkText).width,x=position.includes('right')?out.width-width-margin:margin,y=position.includes('bottom')?out.height-margin:margin+size;ctx.fillText(w.watermarkText,x,y);}ctx.globalAlpha=1;return out;};

RenderStudio.deviceReport = () => {const s=RenderStudio.getState(),caps=(RenderStudio.engine&&RenderStudio.engine.capabilities)||s.capabilities||{},renderer=RenderStudio.engine&&RenderStudio.engine.renderer,gl=renderer&&renderer.getContext&&renderer.getContext();let vendor='unknown',gpu='unknown';try{const ext=gl&&gl.getExtension('WEBGL_debug_renderer_info');if(ext){vendor=gl.getParameter(ext.UNMASKED_VENDOR_WEBGL);gpu=gl.getParameter(ext.UNMASKED_RENDERER_WEBGL);}}catch(error){}return [`Render Studio ${RenderStudio.VERSION}`,`Blockbench ${typeof Blockbench!=='undefined'&&Blockbench.version||'unknown'}`,`Profile: ${s.performance} (auto: ${!!s.tools.autoProfile})`,`Mobile: ${RenderStudio.isMobile()}`,`User agent: ${typeof navigator!=='undefined'?navigator.userAgent:'unknown'}`,`Memory: ${typeof navigator!=='undefined'&&navigator.deviceMemory||'unknown'} GB`,`CPU threads: ${typeof navigator!=='undefined'&&navigator.hardwareConcurrency||'unknown'}`,`WebGL 2: ${!!caps.webgl2}`,`Max texture: ${caps.maxTexture||'unknown'}`,`Max renderbuffer: ${caps.maxRenderbuffer||'unknown'}`,`GPU vendor: ${vendor}`,`GPU: ${gpu}`,`Output: ${s.output.width}x${s.output.height}`,`Lights: ${s.lights.length}`].join('\n');};
RenderStudio.copyDeviceReport = async () => {const text=RenderStudio.deviceReport();try{if(typeof Blockbench.setClipboardText==='function')Blockbench.setClipboardText(text);else await navigator.clipboard.writeText(text);Blockbench.showQuickMessage('Device report copied');}catch(error){new Dialog('render_studio_report',{title:RenderStudio.t('diagnostics'),component:{data(){return{text}},template:'<textarea style="width:100%;height:55vh" readonly :value="text"></textarea>'},buttons:['Close']}).show();}};

RenderStudio.legacyTranslations={
  'Render Scene':'Render Sahnesi','Render Camera':'Render Kamerası','Environment':'Ortam','Presets':'Hazır Ayarlar','Point':'Nokta','Spot':'Spot','Sun':'Güneş','Area':'Alan','Render Properties':'Render Özellikleri','Performance':'Performans','Device':'Cihaz','Camera':'Kamera','Projection':'Projeksiyon','Perspective':'Perspektif','Orthographic':'Ortografik','Current View':'Geçerli Görünüm','Frame Model':'Modeli Kadraja Al','Materials & Shading':'Malzemeler ve Gölgelendirme','Environment & Ground':'Ortam ve Zemin','Output':'Çıktı','Width':'Genişlik','Height':'Yükseklik','Render Tools':'Render Araçları','Custom Presets':'Özel Presetler','Automatic Camera':'Otomatik Kamera','Effects':'Efektler','Render Layers':'Render Katmanları','Background Image':'Arka Plan Görseli','Light Dragging':'Işık Sürükleme','Scene Export':'Sahne Dışa Aktarma','Render History':'Render Geçmişi','Save':'Kaydet','Apply':'Uygula','Clear':'Temizle','Cancel':'İptal','Color':'Renk','Size':'Boyut','Position':'Konum','Rotation':'Döndürme','Intensity':'Yoğunluk','Distance':'Mesafe','Name':'Ad','Cast Shadows':'Gölge Oluştur','Point At Model':'Modele Yönelt','Ground Plane':'Zemin Düzlemi','Shadow Catcher':'Gölge Yakalayıcı','Background':'Arka Plan','Transparent':'Şeffaf','Solid':'Düz Renk','Gradient':'Gradyan','Image':'Görsel'
};
RenderStudio.applyLanguageToDOM = () => {if(typeof document==='undefined'||!document.querySelectorAll)return;const tr=RenderStudio.getState().tools.language==='tr',roots=document.querySelectorAll('#panel_render_studio_scene *,#panel_render_studio_settings *,#panel_render_studio_tools *');for(const element of roots){for(const node of element.childNodes||[]){if(node.nodeType!==3)continue;if(node.__rsEnglish===undefined)node.__rsEnglish=node.nodeValue;const base=node.__rsEnglish,trim=String(base).trim(),translated=RenderStudio.legacyTranslations[trim];node.nodeValue=tr&&translated?base.replace(trim,translated):base;}if(element.placeholder!==undefined){if(element.dataset&&element.dataset.rsEnglishPlaceholder===undefined)element.dataset.rsEnglishPlaceholder=element.placeholder;const base=element.dataset&&element.dataset.rsEnglishPlaceholder||element.placeholder;element.placeholder=tr&&base==='Preset name'?'Preset adı':base;}}};

RenderStudio.patchGLBScene = (buffer,engine) => {
  const input=Object.prototype.toString.call(buffer)==='[object ArrayBuffer]'?buffer:buffer&&buffer.buffer?buffer.buffer.slice(buffer.byteOffset,buffer.byteOffset+buffer.byteLength):null;if(!input)throw new Error('Blockbench returned an unsupported GLB buffer');const view=new DataView(input);if(view.getUint32(0,true)!==0x46546c67)throw new Error('Blockbench returned an invalid GLB file');
  let offset=12,json=null,bin=null;while(offset<input.byteLength){const length=view.getUint32(offset,true),type=view.getUint32(offset+4,true),data=input.slice(offset+8,offset+8+length);if(type===0x4e4f534a)json=JSON.parse(new TextDecoder().decode(data).trim());else if(type===0x004e4942)bin=data;offset+=8+length;}
  if(!json)throw new Error('GLB JSON scene is missing');json.nodes=json.nodes||[];json.scenes=json.scenes||[{nodes:[]}];const scene=json.scenes[json.scene||0],s=RenderStudio.getState();scene.nodes=scene.nodes||[];json.cameras=json.cameras||[];
  engine.updateCamera(s.output.width/Math.max(1,s.output.height));const cameraIndex=json.cameras.push(s.camera.projection==='orthographic'?{name:'Render Camera',type:'orthographic',orthographic:{xmag:s.camera.orthoScale*(s.output.width/Math.max(1,s.output.height)),ymag:s.camera.orthoScale,znear:s.camera.near,zfar:s.camera.far}}:{name:'Render Camera',type:'perspective',perspective:{yfov:THREE.MathUtils.degToRad(s.camera.fov),znear:s.camera.near,zfar:s.camera.far,aspectRatio:s.output.width/Math.max(1,s.output.height)}})-1;
  const cameraNode=json.nodes.push({name:'Render Camera',camera:cameraIndex,translation:s.camera.position.slice(),rotation:engine.camera.quaternion.toArray()})-1;scene.nodes.push(cameraNode);
  json.extensionsUsed=json.extensionsUsed||[];if(!json.extensionsUsed.includes('KHR_lights_punctual'))json.extensionsUsed.push('KHR_lights_punctual');json.extensions=json.extensions||{};const ext=json.extensions.KHR_lights_punctual={lights:[]};
  for(const data of s.lights.filter(light=>light.enabled)){const type=data.type==='directional'?'directional':data.type==='spot'||data.type==='area'?'spot':'point',light={name:data.name,type,color:new THREE.Color(data.color).toArray(),intensity:data.intensity};if(type==='point'&&data.distance)light.range=data.distance;if(type==='spot')light.spot={innerConeAngle:0,outerConeAngle:THREE.MathUtils.degToRad(data.angle||55)};const object=engine.lightObjects.get(data.id),index=ext.lights.push(light)-1,node={name:data.name,translation:data.position.slice(),extensions:{KHR_lights_punctual:{light:index}}};if(object)node.rotation=object.quaternion.toArray();scene.nodes.push(json.nodes.push(node)-1);}
  const encoder=new TextEncoder(),raw=encoder.encode(JSON.stringify(json)),jsonLength=Math.ceil(raw.length/4)*4,binLength=bin?Math.ceil(bin.byteLength/4)*4:0,total=12+8+jsonLength+(bin?8+binLength:0),output=new ArrayBuffer(total),out=new DataView(output),bytes=new Uint8Array(output);out.setUint32(0,0x46546c67,true);out.setUint32(4,2,true);out.setUint32(8,total,true);out.setUint32(12,jsonLength,true);out.setUint32(16,0x4e4f534a,true);bytes.fill(0x20,20,20+jsonLength);bytes.set(raw,20);if(bin){const at=20+jsonLength;out.setUint32(at,binLength,true);out.setUint32(at+4,0x004e4942,true);bytes.set(new Uint8Array(bin),at+8);}return output;
};
RenderStudio.exportGLBScene = async () => {if(!RenderStudio.engine||!Project)return;try{if(typeof Codecs==='undefined'||!Codecs.gltf)throw new Error('The Blockbench glTF exporter is unavailable');const content=await Codecs.gltf.compile({encoding:'binary',animations:true});const glb=RenderStudio.patchGLBScene(content,RenderStudio.engine);RenderStudio.exportBlob(new Blob([glb],{type:'model/gltf-binary'}),`${RenderStudio.safeName(Project.name)}_render_scene`,'glb','Render Studio GLB Scene');}catch(error){Blockbench.showMessageBox({title:'GLB Export Failed',message:String(error.message||error)});}};

{
  const proto=RenderStudio.Engine.prototype,baseRebuildModel=proto.rebuildModel,baseSyncPose=proto.syncPose,baseRebuildEnvironment=proto.rebuildEnvironment,baseSetBackground=proto.setBackground,baseInstallInteraction=proto.installInteraction;
  proto.disposeOutline=function(){if(this.outlineModel){this.scene.remove(this.outlineModel);this.outlineModel.traverse(node=>{if(node.material&&node.userData.renderStudioOutline)node.material.dispose();});this.outlineModel=null;}this.outlineMap=[];};
  proto.rebuildOutline=function(){this.disposeOutline();const settings=RenderStudio.getState().post;if(!settings.outline||!this.model)return;this.outlineModel=this.model.clone(true);this.outlineModel.name='Render Studio Outline';const source=[],outline=[];this.model.traverse(node=>source.push(node));this.outlineModel.traverse(node=>outline.push(node));this.outlineMap=[];for(let i=0;i<outline.length;i++){const node=outline[i],src=source[i];this.outlineMap.push([src,node]);if(node.isMesh){node.material=new THREE.ShaderMaterial({uniforms:{outlineColor:{value:new THREE.Color(settings.outlineColor)},outlineSize:{value:RenderStudio.clamp(settings.outlineSize,.001,1)}},vertexShader:'uniform float outlineSize; void main(){vec3 p=position+normal*outlineSize;gl_Position=projectionMatrix*modelViewMatrix*vec4(p,1.0);}',fragmentShader:'uniform vec3 outlineColor; void main(){gl_FragColor=vec4(outlineColor,1.0);}',side:THREE.BackSide,depthTest:true,depthWrite:true});node.userData.renderStudioOutline=true;node.castShadow=false;node.receiveShadow=false;}else if(node.isLine||node.isPoints||node.isSprite)node.visible=false;}this.scene.add(this.outlineModel);};
  proto.rebuildModel=function(){this.disposeOutline();baseRebuildModel.call(this);this.rebuildOutline();};
  proto.syncPose=function(){baseSyncPose.call(this);if(this.outlineMap)for(const [source,target] of this.outlineMap){target.position.copy(source.position);target.quaternion.copy(source.quaternion);target.scale.copy(source.scale);target.visible=source.visible;}if(this.outlineModel)this.outlineModel.updateMatrixWorld(true);};
  proto.updateBackgroundTexture=function(){const env=RenderStudio.getState().environment;if(this.backgroundTexture){this.backgroundTexture.dispose();this.backgroundTexture=null;}if(env.background!=='image'||!env.imageData)return;new THREE.TextureLoader().load(env.imageData,texture=>{if(this.backgroundTexture)this.backgroundTexture.dispose();this.backgroundTexture=texture;if('colorSpace' in texture&&THREE.SRGBColorSpace)texture.colorSpace=THREE.SRGBColorSpace;else if('encoding' in texture&&THREE.sRGBEncoding)texture.encoding=THREE.sRGBEncoding;this.invalidate();},undefined,error=>console.warn('[Render Studio] Background texture failed',error));};
  proto.rebuildEnvironment=function(){baseRebuildEnvironment.call(this);this.updateBackgroundTexture();};
  proto.setBackground=function(final=false){const env=RenderStudio.getState().environment;if(env.background==='image'&&this.backgroundTexture){this.scene.background=this.backgroundTexture;this.renderer.setClearColor(0x000000,1);return;}baseSetBackground.call(this,final);};
  proto.beginRenderPass=function(pass){const s=RenderStudio.getState(),restore={pass:s.output.pass,background:s.environment.background,override:this.scene.overrideMaterial,outlineVisible:this.outlineModel&&this.outlineModel.visible,groundMaterial:this.ground&&this.ground.material,groundVisible:this.ground&&this.ground.visible,materials:[]},temporary=[];if(this.outlineModel)this.outlineModel.visible=pass==='beauty';if(pass==='transparent')s.environment.background='transparent';else if(pass==='normal'){const material=new THREE.MeshNormalMaterial();this.scene.overrideMaterial=material;temporary.push(material);s.environment.background='transparent';if(this.ground)this.ground.visible=false;}else if(pass==='depth'){const material=new THREE.MeshDepthMaterial({depthPacking:THREE.BasicDepthPacking});this.scene.overrideMaterial=material;temporary.push(material);s.environment.background='solid';s.environment.color='#ffffff';if(this.ground)this.ground.visible=false;}else if(pass==='shadow'){s.environment.background='solid';restore.color=s.environment.color;s.environment.color='#ffffff';if(this.model)this.model.traverse(node=>{if(node.isMesh){const mats=Array.isArray(node.material)?node.material:[node.material];for(const material of mats){if(material){restore.materials.push([material,material.colorWrite]);material.colorWrite=false;}}}});if(this.ground){const material=new THREE.ShadowMaterial({color:0x000000,opacity:1});this.ground.material=material;temporary.push(material);this.ground.visible=true;}}return()=>{this.scene.overrideMaterial=restore.override;if(this.outlineModel)this.outlineModel.visible=restore.outlineVisible;if(this.ground){this.ground.material=restore.groundMaterial;this.ground.visible=restore.groundVisible;}for(const [material,colorWrite] of restore.materials)material.colorWrite=colorWrite;s.environment.background=restore.background;if(restore.color)s.environment.color=restore.color;temporary.forEach(material=>material.dispose());};};
  proto.installLightDragInteraction=function(){const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2(),plane=new THREE.Plane(),point=new THREE.Vector3();raycaster.params.Line=raycaster.params.Line||{};raycaster.params.Line.threshold=1;let active=null;const locate=e=>{const rect=this.canvas.getBoundingClientRect();pointer.x=(e.clientX-rect.left)/Math.max(1,rect.width)*2-1;pointer.y=-(e.clientY-rect.top)/Math.max(1,rect.height)*2+1;raycaster.setFromCamera(pointer,this.camera);};this.canvas.addEventListener('pointerdown',e=>{if(!RenderStudio.getState().tools.dragLights)return;locate(e);const hit=raycaster.intersectObjects([...this.helpers.values()],true).find(item=>{let object=item.object;while(object&&!object.userData.lightId)object=object.parent;return object&&object.userData.lightId;});if(!hit)return;let object=hit.object;while(object&&!object.userData.lightId)object=object.parent;active=object.userData.lightId;const light=this.lightObjects.get(active);if(!light){active=null;return;}RenderStudio.beginUndoAction();plane.setFromNormalAndCoplanarPoint(this.camera.getWorldDirection(new THREE.Vector3()),light.position);RenderStudio.getState().selectedLight=active;e.preventDefault();e.stopImmediatePropagation();},{capture:true});this.canvas.addEventListener('pointermove',e=>{if(!active)return;locate(e);if(raycaster.ray.intersectPlane(plane,point)){const data=RenderStudio.getState().lights.find(light=>light.id===active);if(data){data.position=point.toArray();this.updateLight(data);RenderStudio.touch();}}e.preventDefault();e.stopImmediatePropagation();},{capture:true});const release=e=>{if(!active)return;active=null;RenderStudio.endUndoAction();e.preventDefault();e.stopImmediatePropagation();};this.canvas.addEventListener('pointerup',release,{capture:true});this.canvas.addEventListener('pointercancel',release,{capture:true});};
  proto.installInteraction=function(){this.installLightDragInteraction();this.canvas.addEventListener('pointerdown',()=>RenderStudio.beginUndoAction());this.canvas.addEventListener('wheel',()=>{RenderStudio.beginUndoAction();clearTimeout(this.renderStudioWheelUndo);this.renderStudioWheelUndo=setTimeout(()=>RenderStudio.endUndoAction(),180);},{capture:true});baseInstallInteraction.call(this);const finish=()=>RenderStudio.endUndoAction();this.canvas.addEventListener('pointerup',finish);this.canvas.addEventListener('pointercancel',finish);};
  const baseDispose=proto.dispose;proto.dispose=function(force){this.disposeOutline();if(this.backgroundTexture){this.backgroundTexture.dispose();this.backgroundTexture=null;}baseDispose.call(this,force);};

  proto.renderImage=async function(options={}){const s=RenderStudio.getState(),out=s.output,pass=options.pass||out.pass||'beauty',manageBusy=options.manageBusy!==false,size=RenderStudio.constrainOutput(out.width,out.height,s.performance),mobileScale=s.performance==='phone'?Math.min(1,1024/Math.max(size.width,size.height)):1,w=Math.max(16,Math.round(size.width*mobileScale)),h=Math.max(16,Math.round(size.height*mobileScale)),tile=Math.min(s.performance==='phone'?256:out.tileSize,this.capabilities.safeSingle,w,h);out.width=w;out.height=h;if(manageBusy){s.render.busy=true;s.render.cancel=false;}const result=document.createElement('canvas');result.width=w;result.height=h;const ctx=result.getContext('2d',{alpha:true});if(!ctx)throw new Error('This device could not allocate the render image. Try a smaller resolution.');const cols=Math.ceil(w/tile),rows=Math.ceil(h/tile),total=cols*rows;let done=0,restorePass=this.beginRenderPass(pass);this.configurePerformance();this.configureRenderer();this.setBackground(true);this.syncPose();this.updateCamera(w/h);const cam=this.camera;
    try{for(let y=0;y<rows;y++)for(let x=0;x<cols;x++){if(s.render.cancel)throw new Error('Render cancelled');const tw=Math.min(tile,w-x*tile),th=Math.min(tile,h-y*tile);this.renderer.setSize(tw,th,false);cam.setViewOffset(w,h,x*tile,y*tile,tw,th);this.renderer.clear();this.renderer.render(this.scene,cam);if(pass==='beauty'&&RenderStudio.getState().helpers===false){}ctx.drawImage(this.renderer.domElement,x*tile,y*tile,tw,th);done++;s.render.progress=Math.round(done/total*100);s.render.status=`Rendering ${pass} ${done} / ${total}`;RenderStudio.refreshUI();await new Promise(resolve=>setTimeout(resolve,0));}if(s.environment.background==='gradient'&&pass==='beauty'){ctx.globalCompositeOperation='destination-over';const gradient=ctx.createLinearGradient(0,0,0,h);gradient.addColorStop(0,s.environment.top);gradient.addColorStop(1,s.environment.bottom);ctx.fillStyle=gradient;ctx.fillRect(0,0,w,h);ctx.globalCompositeOperation='source-over';}let finalCanvas=(pass==='beauty'||pass==='transparent')?RenderStudio.applyCanvasEffects(result):result;if(pass==='beauty'||pass==='transparent')finalCanvas=await RenderStudio.applyWatermark(finalCanvas);if(options.history!==false)RenderStudio.addHistory(finalCanvas,pass);if(options.show!==false)this.showResult(finalCanvas);return finalCanvas;}
    finally{cam.clearViewOffset();restorePass();if(manageBusy){s.render.busy=false;s.render.status='';}this.resize();RenderStudio.refreshUI();}
  };
  const passBase=proto.beginRenderPass;proto.beginRenderPass=function(pass){const color=RenderStudio.getState().environment.color,restore=passBase.call(this,pass);return()=>{restore();RenderStudio.getState().environment.color=color;};};
}
